# Use root/example as user/password credentials
version: '3.1'

services:
  db: 
    image: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_USER=gokhan
      - MARIADB_PASSWORD=userpassword
      - MARIADB_HOST=%
    ports:
      - 3306:3306
  
  server:
    build: ./server
    restart: always
    ports:
      - 5000:8080

  client:
    build: ./client
    restart: always
    ports: 
    - 8080:8080
